name: EntityInspector
version: 1.2.55
main: com.example.entityinspector.EntityInspector
api-version: 1.20
commands:
  entityinspector:
    description: Main command for EntityInspector
    usage: /entityinspector <inspect|i|search|s>
