name: EntityInspector
version: 1.0
main: com.example.entityinspector.EntityInspector
api-version: 1.20
commands:
  ec:
    description: Main command for EntityInspector
    usage: /ec <inspect|i|search|s>
